version: "3.8"
volumes:
  static_dir:
  media_dir:
  pg_data:

services:
  db:
    image: postgres:15.3-alpine
    restart: on-failure
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - ../.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: byjiat/foodgram_backend:master
    restart: on-failure
    volumes:
      - static_dir:/app/static/
      - media_dir:/app/media/
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    env_file:
      - ../.env

  frontend:
    image: byjiat/foodgram_frontend:master
    volumes:
      - ../frontend/:/app/result_build/
    env_file:
      - ../.env

  nginx:
    image: nginx:1.23.3
    restart: on-failure
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_dir:/etc/nginx/html/static/
      - media_dir:/etc/nginx/html/media/
    depends_on:
      - backend
    env_file:
      - ../.env

