version: '3.3'
volumes:
  static_dir:
  media_dir:
  pg_data:

services:
  db:
    image: postgres:15.3
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - ../.env
    healthcheck:
      test: pg_isready -U foodgram -d foodgram
      interval: 50s
      timeout: 3s
      retries: 3

  backend:
    build:
      context: "../"
      dockerfile: ./backend/Dockerfile
    restart: always
    volumes:
      - static_dir:/app/static/
      - media_dir:/app/media/
    depends_on:
      - db
    env_file:
      - ../.env

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    image: nginx:1.23.3-alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static_dir:/var/html/static/
      - media_dir:/var/html/media/
    depends_on:
      - backend
    env_file:
      - ../.env

