# Generated by Django 4.2.3 on 2023-07-14 07:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0005_alter_recipeingredient_ingredient_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipe",
            options={
                "ordering": ("-id",),
                "verbose_name": "Recipe",
                "verbose_name_plural": "Recipes",
            },
        ),
    ]
